### ISSUE TITLE
Change name of filter_ambiguous_tags to filter_ambiguous_indices

### ISSUE THREAD

**Issue by cajwalsh** [mhoban/eDNAFlow#19]
I appreciate you changing the name of the argument and keeping both ways of saying it as valid options. I noticed the name of the process still says tags though. Would you consider changing it to indices on (currently) lines 59, 62, 68, 72 and 605 (I think that's all) so it shows up as indices in the file names and CLI progress reports? Besides just wanting to name them correctly, I imagine this could be a point of confusion in the case where someone uses both illumina indices and tagged primers on the same sequencing run. This process only deals with ambiguous indices while ambiguous tags on metabarcoding primers would be dealt with in ngsfilter. Thanks!

**Comment by mhoban** [comment]
I just went ahead and change 'tags' to 'indices' across the board.  This is fixed in commit 46e30d1c8245a88c958ac5e6bb5f77b719f2f690
