### ISSUE TITLE
Improve error message when attempting to run eDNA flow on .gz files

### ISSUE THREAD

**Issue by vwishingrad** [mhoban/eDNAFlow#22]
If a user attempts to (incorrectly) run the analysis on .gz files, it will. not return an error indicating the issue with compressed files. This could be a welcome addition.

**Comment by vwishingrad** [comment]
Or maybe if the user tries to run on .gz files, gunzip them automatically and provide a message?

**Comment by mhoban** [comment]
This is essentially a duplicate of #11, which will be resolved shortly by supporting gzipped files.
