### ISSUE TITLE
Nextflow fails at the dereplication stage when no primer matches are found by ngsfilter

### ISSUE THREAD

**Issue by cajwalsh** [mhoban/eDNAFlow#33]
Following up on our conversation from earlier, you mentioned it would be nice to program in a graceful fail when there are no sequences that pass the primer check in ngsfilter. I decided to run eDNAFlow on a COI library using a 12S marker to check if some 12S amplicon contamination might have ended up in the sequencing run too. After making it through ngsfilter with empty files, eDNAFlow got through "merging" all "files" before vsearch couldn't find any fasta sequences to start dereplicating. If you want the eDNAFlow files/folder/output, they're on kinilau: /home/cajw/working/eDNA/contam_tests/NIUE

**Comment by mhoban** [comment]
It looks like in nextflow there's no way to fail in a way that I would consider graceful. I can provide a better message, but there's no way to avoid seeing the whole ugly error screen including the script contents and everything.

![image](https://github.com/mhoban/eDNAFlow/assets/3262131/fbbd0045-0bb1-4134-be07-9642068a7f4f)

You can see in the "command error" section, it's now more informative, but there's still all that other garbage.
