### ISSUE TITLE
Change file extensions from ".tab" to ".tsv"

### ISSUE THREAD

**Issue by vwishingrad** [mhoban/eDNAFlow#36]
Suggestion to change output file extensions from ".tab" to ".tsv" to enable remote fast preview on osx

**Comment by mhoban** [comment]
Good call. Maybe an option that allows the extension to specified, but it defaults to .tsv?

**Comment by vwishingrad** [comment]
Sure--though I don't think allowing the extension to be specified is necessary--I just want .tsv... but totally up to you

**Comment by mhoban** [comment]
I guess there's not really a good reason to have the extension customizable other than that I find .tab more aesthetically appealing that .tsv. But if tsv is more useful, that's what we'll use!

**Comment by mhoban** [comment]
This is changed in the development code, which will soon be deployed
