### ISSUE TITLE
Provide OTU table merged with insect taxonomy

### ISSUE THREAD

**Issue by mhoban** [mhoban/eDNAFlow#46]
The taxonomy collapser script produces an OTU table including the taxonomic hierarchy. The insect output should do the same and spit it out alongside the classification table you already get.

**Comment by cajwalsh** [comment]
I have something that puts the two together here, using the code you wrote to fill in the domain in the process:
https://github.com/cajwalsh/eDNAnalyze/blob/main/R/insect_merge.R
Right now I only keep a few columns of info from insect and remove insect taxonomy for entries that had blast taxonomy (in case they are conflicting). There's also a simple script/function to merge different levels of lca assignment as lca_progression too if you're interested in adding more to the pipeline.

**Comment by mhoban** [comment]
This is now done in 886631080903e10d5798703865cbd5e8575dc70b. (As of this comment, it hasn't been deployed but it will be soon).
