### ISSUE TITLE
option to skip primer mismatch filter in ngsfilter command/process

### ISSUE THREAD

**Issue by cajwalsh** [mhoban/eDNAFlow#68]
I have a collaborator who wants me to run eDNAFlow on their data to test it against the pipeline they always used. However, the fastqs they received from the folks that did their sequencing (a while back) already have the metabarcoding primer sequences removed from the fastqs. So this is a feature request to add an option to run the ngsfilter process without the primer mismatch filtering (ngsfilter -e) if a --skip-primer-match flag is used (e.g. as an "if" option in the ngsfilter process to change the script used like "exec_denoiser" or an alternate ngsfilter process). I'd be okay to work on this myself if you wanted.

**Comment by mhoban** [comment]
Done as of d122017744619eadbfc896e9830e59138bda37c5 (pull-request merge from @cajwalsh)
